obstacles:
  - corners:
    - [2.0, 2.0]
    - [2.0, 1.8]
    - [1.0, 1.8]
    - [1.0, 2.0]
  - corners:
    - [0.0, 3.0]
    - [0.0, 2.8]
    - [1.0, 2.8]
    - [1.0, 3.0]
  - corners:
    - [1.0, 0.0]
    - [1.0, 0.0]
    - [1.0, 1.0]
    - [1.0, 0.0]
viewpoints:
  - x: 0.5
    y: 0.65
    z: -0.5
    qx: 0.0
    qy: 0.0
    qz: 0.0
    qw: 0.7071
    frame_id: "map"
  - x: 1.5
    y: 0.65
    z: -0.5
    qx: 0.0
    qy: 0.0
    qz: 0.7071
    qw: 0.7071
    frame_id: "map"
  - x: 0.65
    y: 3.60
    z: -0.5
    qx: 0.0
    qy: 0.0
    qz: -0.7071
    qw: 0.7071
    frame_id: "map"
